[project]
name = "falco-starter-template"
version = "0.1.0"
description = "Falco project starter template"
readme = "README.md"
authors = [
    { name = "Tobi", email = "tobidegnon@proton.me" }
]
requires-python = ">=3.12"
dependencies = [
    "shibuya>=2024.12.15",
    "sphinx>=8.1.3",
]

