name: CI

on:
  pull_request:
    branches: ['master', 'main']

  push:
    branches: ['master', 'main']

jobs:
  create-project:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install falco
        run: |
          pip install falco-cli --pre

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Generate a project
        run: falco start-project test-project -b /home/runner/work/falco_blueprint_basic/falco_blueprint_basic --skip-new-version-check
        working-directory: ./

      - name: Install hatch
        run: |
          pip install hatch

      - name: Run django checks
        run: |
          cd test_project && hatch run python manage.py check --fail-level WARNING

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install falco
        run: |
          pip install falco-cli --pre

      - name: Generate a project
        run: falco start-project test-project -b /home/runner/work/falco_blueprint_basic/falco_blueprint_basic --skip-new-version-check
        working-directory: ./

      - name: Build image
        uses: docker-practice/actions-setup-docker@master
        run: |
          cd test_project
          docker build . -f docker/Dockerfile


